build: false
shallow_clone: false
skip_branch_with_pr: true
clone_depth: 1

environment:

  matrix:
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - cmd: set PATH=%python%;%python%\scripts;%PATH%
install:
  - cmd: |
        pip install --upgrade pip wheel
        pip --version
  - cmd: |
        pip install --pre -e . coverage nose_warnings_filters
        pip install ipykernel[test] nose-timer
  - cmd: |
        pip install matplotlib numpy
        pip freeze
  - cmd: python -c "import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)"
test_script:
  - cmd: nosetests --with-coverage --with-timer --cover-package=ipykernel ipykernel

on_success:
  - cmd: pip install codecov
  - cmd: codecov
