package:
  name: yap4py
  version: 6.5.0

requirements:
  ignore_prefix_files:
    - startup.yss
  build:
    - cmake
    - swig
    - gmp
    - ninja
    - readline
    - python
    - r
    - notebook
    - pkgconfig
    - libxml2
run:
    - jupyterlab
    - python
    - readline
    - gmp
    - r
    - notebook
    - libxml2
about:
    home: http://www.github.com/vscosta/yap-6.3.git
    license: LGPL2
    license_family: LGPL
    summary: Prolog System

source:
  git_url: ..
  git_rev: master
